<?php

namespace UkronicBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
	function countForUser(User $user){
		return 585;
	}

	public function countComments(){
		$q = $this->getEntityManager()
		->createQuery("SELECT COUNT(DISTINCT u.id) FROM UkronicBundle:Comment u");
    	$nb = $q->getSingleScalarResult();

		return $nb;
	}
}
