<?php

namespace UkronicBundle\Repository;
use UkronicBundle\Entity\User;


/**
 * HistoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoRepository extends \Doctrine\ORM\EntityRepository
{
	function lastNews(User $user){
		$monId = $user->getId();
		$q = $this->getEntityManager()
		->createQuery("SELECT h FROM UkronicBundle:Histo h JOIN h.user u WHERE u.id = $monId ORDER BY h.dateAction DESC " )
		->setMaxresults(5);
    	return $q->getResult();
		
	}
}
