<?php

namespace UkronicBundle\Repository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends \Doctrine\ORM\EntityRepository
{

	function allMovies(){
		$q = $this->getEntityManager()
		->createQuery("SELECT m FROM UkronicBundle:Movie m   WHERE m.typeMovie = 'F' ORDER BY m.title" );
    	$movies = $q->getResult();
		return $movies;
	}

	function allSeries(){
		$q = $this->getEntityManager()
		->createQuery("SELECT m FROM UkronicBundle:Movie m   WHERE m.typeMovie = 'S' ORDER BY m.title" );
    	$series = $q->getResult();
		return $series;
	}

	public function countMovies(){
		$q = $this->getEntityManager()
		->createQuery("SELECT COUNT(DISTINCT u.id) FROM UkronicBundle:Movie u WHERE u.typeMovie = 'F'");
    	$nb = $q->getSingleScalarResult();

		return $nb;
	}
	
	public function countSeries(){
		$q = $this->getEntityManager()
		->createQuery("SELECT COUNT(DISTINCT u.id) FROM UkronicBundle:Movie u WHERE u.typeMovie = 'S'");
    	$nb = $q->getSingleScalarResult();

		return $nb;
	}

	public function findEpisodeSerie($id,$season,$episode){
		$q = $this->getEntityManager()
		->createQuery("SELECT m FROM UkronicBundle:Movie m WHERE m.number = $id AND m.season = $season AND m.episode = $episode");
		return $q->getResult();
	}
	
}
