<?php

namespace UkronicBundle\Repository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends \Doctrine\ORM\EntityRepository
{

	function allMovies(){
		$q = $this->getEntityManager()
		->createQuery("SELECT m FROM UkronicBundle:Movie m   WHERE m.typeMovie = 'F' ORDER BY m.title" );
    	$movies = $q->getResult();
		return $movies;
	}

	function allSeries(){
		$q = $this->getEntityManager()
		->createQuery("SELECT m FROM UkronicBundle:Movie m   WHERE m.typeMovie = 'S' ORDER BY m.title" );
    	$series = $q->getResult();
		return $series;
	}
	
}
