<?php

namespace UkronicBundle\Repository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends \Doctrine\ORM\EntityRepository
{
	function trouve(User $user, Movie $movie){
		$rating = $this->findOneBy(array("user"=>$user,"movie"=>$movie);
			return $rating;
	}
}
