<?php

namespace UkronicBundle\Repository;

/**
 * SignalementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignalementRepository extends \Doctrine\ORM\EntityRepository
{


	public function countSignalements(){
		$q = $this->getEntityManager()
		->createQuery("SELECT COUNT(DISTINCT u.id) FROM UkronicBundle:Signalement u WHERE u.status = 'A'");
    	$nb = $q->getSingleScalarResult();

		return $nb;
	}

	public function allAlerts(){
		$q = $this->getEntityManager()
		->createQuery("SELECT u FROM UkronicBundle:Signalement u WHERE u.status = 'A'");
    	$tab = $q->getResult();

		return $tab;
	}

}
