<?php

namespace UkronicBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

	public function countUsers(){
		$q = $this->getEntityManager()
		->createQuery("SELECT COUNT(DISTINCT u.id) FROM UkronicBundle:User u WHERE u.enabled = 1");
    	$nb = $q->getSingleScalarResult();

		return $nb;
	}
}
