user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /



app:
    resource: "@UkronicBundle/Controller/"
    type:     annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"