# src/OC/PlatformBundle/Resources/config/services.yml

parameters:

    app.file.twig.extension.class: UkronicBundle\Twig\Extension\FileExtension

services:
    ukronic.infomovie:
        class: UkronicBundle\InfoMovie\InfoMovie
        arguments: [%tmdb_api_key%]
    ukronic.imageuser:
        class: UkronicBundle\ImageUser\ImageUser
    app.file.twig.extension:
        class: %app.file.twig.extension.class%
        tags:
            - { name: twig.extension }
