# src/OC/PlatformBundle/Resources/config/services.yml

services:
    ukronic.infomovie:
        class: UkronicBundle\InfoMovie\InfoMovie
    ukronic.imageuser:
        class: UkronicBundle\ImageUser\ImageUser